import { Head, useForm, usePage } from '@inertiajs/react';
import type { PageProps } from '@/types';
import AdminLayout from '@/layouts/AdminLayout';
import { Breadcrumbs, FormField, Notification } from '@/components/admin/AdminLayoutParts';

export default function Index({ categories }: { categories: Array<{ id: number; name: string; slug: string; type: string; posts_count: number }> }) {
    const { flash } = usePage<PageProps<{ flash?: { success?: string } }>>().props;
    const { data, setData, post, processing } = useForm({ name: '', slug: '', type: 'blog' });
    return <AdminLayout><Head title="Media Categories" /><div className="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><Breadcrumbs items={['Admin', 'Media', 'Categories']} /><h1 className="text-3xl font-semibold">Media categories</h1><Notification message={flash?.success} /><form onSubmit={(event) => { event.preventDefault(); post('/admin/media/categories'); }} className="grid gap-3 rounded-xl border border-slate-800 bg-slate-950 p-5 sm:grid-cols-4"><FormField label="Name"><input value={data.name} onChange={(event) => setData('name', event.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2" /></FormField><FormField label="Slug"><input value={data.slug} onChange={(event) => setData('slug', event.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2" /></FormField><FormField label="Type"><select value={data.type} onChange={(event) => setData('type', event.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2"><option value="press">Press</option><option value="blog">Blog</option><option value="general">General</option></select></FormField><button disabled={processing} className="self-end rounded-lg bg-emerald-600 px-4 py-2 text-sm">Add category</button></form><div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-950"><table className="w-full text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Name</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Posts</th></tr></thead><tbody>{categories.map((category) => <tr key={category.id} className="border-b border-slate-800/70"><td className="px-4 py-4">{category.name}</td><td className="px-4 py-4 text-slate-400">{category.type}</td><td className="px-4 py-4 text-slate-400">{category.posts_count}</td></tr>)}</tbody></table></div></div></AdminLayout>;
}
