<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PageSection;

class PageSectionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sections = [
            ['page_key' => 'home', 'section_key' => 'hero', 'section_type' => 'home.hero', 'content_snapshot' => ['heading' => 'Designed for the Way You Live', 'description' => 'Discover thoughtfully designed communities that combine architectural excellence, lasting value, and a lifestyle built around comfort and elegance.', 'cta_label' => "Our Project's", 'cta_url' => '/projects', 'background_image' => 'assets/herobg.png', 'hero_image' => 'assets/tower_img.png']],
            ['page_key' => 'home', 'section_key' => 'stats', 'section_type' => 'home.stats', 'content_snapshot' => ['items' => [['value' => '40+', 'label' => 'Experience'], ['value' => '60+', 'label' => 'Projects'], ['value' => '15k', 'label' => 'Clients'], ['value' => '2', 'label' => 'Countries']]]],
            ['page_key' => 'home', 'section_key' => 'gallery', 'section_type' => 'home.gallery', 'content_snapshot' => ['eyebrow' => 'Our Gallery', 'heading' => 'Spaces That Inspire', 'description' => 'A glimpse into the details, designs, and destinations that define the LARZ experience.', 'cta_label' => 'Explore All', 'cta_url' => '/projects']],
            ['page_key' => 'home', 'section_key' => 'featured_projects', 'section_type' => 'home.featured_projects', 'content_snapshot' => ['eyebrow' => 'Featured Projects', 'heading' => 'Our Signature Developments', 'description' => 'Discover a curated selection of our most prestigious projects, designed to elevate the standard of modern living.', 'cta_label' => 'Explore All', 'cta_url' => '/projects']],
            ['page_key' => 'home', 'section_key' => 'final_cta', 'section_type' => 'home.final_cta', 'content_snapshot' => ['eyebrow' => 'Get started', 'heading' => 'Ready to find your next home?', 'description' => 'Explore our communities or speak with our team to find the right fit.', 'cta_label' => 'View projects', 'cta_url' => '/projects']],
            ['page_key' => 'about', 'section_key' => 'hero', 'section_type' => 'about.hero', 'content_snapshot' => ['eyebrow' => 'About LARZ', 'heading' => "You're not choosing a building. You're choosing how you'll live.", 'description' => 'For more than 40 years, our founders have been learning how to get that right — across New Cairo and the New Administrative Capital.', 'background_image' => 'assets/TYPE-B-IMAGE-01.png', 'cta_label' => 'Explore our projects', 'cta_url' => '/projects', 'secondary_cta_label' => 'Contact us', 'secondary_cta_url' => '/contact-us']],
            ['page_key' => 'about', 'section_key' => 'stats', 'section_type' => 'about.stats', 'content_snapshot' => ['items' => [['value' => '60+', 'label' => 'Projects', 'note' => 'Completed & ongoing'], ['value' => '2', 'label' => 'Countries', 'note' => 'Egypt & expanding'], ['value' => '15k+', 'label' => 'Clients', 'note' => 'Families & businesses'], ['value' => '40+', 'label' => 'Years', 'note' => 'Founding experience']]]],
            ['page_key' => 'about', 'section_key' => 'story', 'section_type' => 'about.story', 'content_snapshot' => ['eyebrow' => 'Our story', 'heading' => 'Why it matters who builds it.', 'body' => "Somewhere to belong. Space to breathe. A home that still feels right in ten years. That's what you're really looking for — and it's what we set out to build. You feel 40 years of experience in the things that are easy to miss and expensive to get wrong: how the morning light falls, how a neighbourhood holds together, how a home lives long after you've moved in. Every choice we make protects something you care about — how your home feels, what it costs to run, and what it's worth years from now.", 'image' => 'assets/IMAGE-01-RENDERED-1.png']],
            ['page_key' => 'about', 'section_key' => 'promise', 'section_type' => 'about.promise', 'content_snapshot' => ['eyebrow' => 'Our promise', 'heading' => "We build places that are still worth it long after the keys change hands.", 'primary_cta_label' => 'Explore our projects', 'primary_cta_url' => '/projects', 'secondary_cta_label' => 'Talk to us', 'secondary_cta_url' => '/contact-us']],
            ['page_key' => 'about', 'section_key' => 'partners', 'section_type' => 'about.partners', 'content_snapshot' => ['eyebrow' => 'Partners & affiliations', 'heading' => 'Built with people who share our standards.', 'description' => 'Architects, engineers and contractors we trust on every project.']],
            ['page_key' => 'about', 'section_key' => 'awards', 'section_type' => 'about.awards', 'content_snapshot' => ['eyebrow' => 'Awards & achievements', 'heading' => 'Recognised for building things that last.']],
            ['page_key' => 'contact', 'section_key' => 'hero', 'section_type' => 'contact.hero', 'content_snapshot' => ['eyebrow' => 'Contact us', 'heading' => "Let's talk.", 'description' => "Whether you're choosing a home or exploring a partnership, we're here — and we answer quickly.", 'primary_cta_label' => 'Request pricing & a tour', 'primary_cta_url' => '#request', 'secondary_cta_label' => 'WhatsApp us', 'secondary_cta_url' => '#whatsapp']],
            ['page_key' => 'contact', 'section_key' => 'contact_methods', 'section_type' => 'contact.contact_methods', 'content_snapshot' => ['eyebrow' => 'Get in touch', 'heading' => 'However suits you best.', 'description' => 'Reach the team through whichever channel works best for you.', 'items' => [['key' => 'hotline', 'icon' => 'phone', 'title' => 'Hotline', 'value' => '15813', 'note' => 'Sat–Thu, 9am–6pm'], ['key' => 'whatsapp', 'icon' => 'message-circle', 'title' => 'WhatsApp', 'value' => '+20 15813', 'note' => 'Fast replies, every day'], ['key' => 'email', 'icon' => 'mail', 'title' => 'Email', 'value' => 'info@larzdevelopments.com', 'note' => 'larzdevelopments.com'], ['key' => 'sales_office', 'icon' => 'map-pin', 'title' => 'Sales office', 'value' => 'New Cairo', 'note' => 'Kov mall, beside Mivida gate 6']]]],
            ['page_key' => 'contact', 'section_key' => 'request_form', 'section_type' => 'contact.request_form', 'content_snapshot' => ['eyebrow' => 'Request pricing / tour', 'heading' => 'Send us a message.', 'description' => 'Tell us what you are looking for and our team will respond within one business day.', 'submit_label' => 'Send message']],
            ['page_key' => 'contact', 'section_key' => 'social_media', 'section_type' => 'contact.social_media', 'content_snapshot' => ['eyebrow' => 'Social media', 'heading' => 'Follow LARZ.', 'description' => 'News, launches and behind-the-scenes moments from across our communities.']],
            ['page_key' => 'contact', 'section_key' => 'location', 'section_type' => 'contact.location', 'content_snapshot' => ['heading' => 'Find us.', 'image' => 'assets/Gallery_5.png']],
            ['page_key' => 'careers', 'section_key' => 'hero', 'section_type' => 'careers.hero', 'content_snapshot' => ['eyebrow' => 'Careers', 'heading' => 'Build your future while we build communities.', 'description' => 'Join a team that cares about getting the details right — and about the people who get them there.']],
            ['page_key' => 'careers', 'section_key' => 'values', 'section_type' => 'careers.values', 'content_snapshot' => ['translations' => ['en' => ['eyebrow' => 'Why LARZ', 'heading' => 'Grow with a team that builds things that last.', 'description' => 'We hire people who care about the details — and about each other.']]]],
            ['page_key' => 'careers', 'section_key' => 'vacancies_settings', 'section_type' => 'careers.vacancies_settings', 'content_snapshot' => ['eyebrow' => 'Vacancies', 'heading' => 'Open roles.', 'description' => 'Join us in shaping communities across New Cairo and beyond.']],
            ['page_key' => 'careers', 'section_key' => 'internship', 'section_type' => 'careers.internship', 'content_snapshot' => ['eyebrow' => 'Internship programs', 'heading' => 'Start your career with us.', 'description' => 'Our internships give students and recent graduates real work across design, marketing, sales and engineering – with mentorship from people who\'ve done it for decades.', 'cta_label' => 'Apply for an internship', 'image' => 'assets/DSC04142-HDR.jpg']],
            ['page_key' => 'careers', 'section_key' => 'general_cv_cta', 'section_type' => 'careers.general_cv_cta', 'content_snapshot' => ['eyebrow' => 'Careers', 'heading' => "Don\u2019t see your role? Send us your CV.", 'cta_label' => 'Send your CV']],
            ['page_key' => 'media', 'section_key' => 'hero', 'section_type' => 'media.hero', 'content_snapshot' => ['eyebrow' => 'Media', 'heading' => 'The latest from LARZ.', 'description' => 'News, stories and moments from across our communities.']],
            ['page_key' => 'media', 'section_key' => 'news', 'section_type' => 'media.news', 'content_snapshot' => ['eyebrow' => 'News & press releases', 'heading' => "What's happening at LARZ.", 'description' => 'Latest announcements and milestones from across our projects and communities.']],
            ['page_key' => 'media', 'section_key' => 'stories', 'section_type' => 'media.stories', 'content_snapshot' => ['eyebrow' => 'Blogs', 'heading' => 'Stories & insight.', 'description' => 'Perspectives and stories from the people shaping our communities.']],
            ['page_key' => 'media', 'section_key' => 'gallery', 'section_type' => 'media.gallery', 'content_snapshot' => ['eyebrow' => 'Photo gallery', 'heading' => 'Inside our communities.', 'description' => 'A glimpse of the spaces, details and moments that define the LARZ experience.', 'images' => ['assets/Gallery_1.png', 'assets/Gallery_2.png', 'assets/Gallery_3.png', 'assets/Gallery_4.png', 'assets/Gallery_5.png', 'assets/project_img_1.png', 'assets/project_img_2.png', 'assets/herobg.png']]],
            ['page_key' => 'media', 'section_key' => 'newsletter', 'section_type' => 'media.newsletter', 'content_snapshot' => ['eyebrow' => 'Newsletter', 'heading' => 'Never miss an update.', 'description' => 'Subscribe to receive our latest news, stories and project milestones directly in your inbox.']],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'hero_slides', 'section_type' => 'project.hero_slides', 'content_snapshot' => ['items' => [['eyebrow' => 'KLOVE   —   New Cairo', 'titleLine1' => 'Come home', 'titleLine2' => 'to quiet.', 'description' => 'A low-rise, green community in New Cairo’s Al-Qornofel — where only a fifth of the land is built on, so your home keeps its light, its air, and its view.'], ['eyebrow' => 'KLOVE   —   New Cairo', 'titleLine1' => 'Live among', 'titleLine2' => 'the green.', 'description' => 'Surrounded by lush landscaped courtyards and open walkways designed to bring nature into every corner of your daily life.'], ['eyebrow' => 'KLOVE   —   New Cairo', 'titleLine1' => 'Light, air,', 'titleLine2' => 'and view.', 'description' => 'Every home is crafted to maximise natural light, fresh air circulation, and unobstructed green views — a rare luxury in urban living.']]]],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'overview', 'section_type' => 'project.overview', 'content_snapshot' => ['heading' => "The city doesn't slow down. Your home should.", 'body' => 'At Klove, you wake up to green instead of traffic, and to space that was planned around the way you actually want to live. Across 24 feddans, only a fifth carries buildings — the rest is garden, water and open air. Nothing rises above five floors, so your mornings stay calm, your evenings stay private, and the view from your window stays yours.']],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'masterplan', 'section_type' => 'project.masterplan', 'content_snapshot' => ['heading' => 'See exactly where your home sits.', 'description' => 'How the green, the water and the walkways wrap around it. Then take the full picture with you.', 'brochureHeading' => 'Get the brochure', 'brochureDescription' => "Two details, and it's yours."]],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'virtual_tour', 'section_type' => 'project.virtual_tour', 'content_snapshot' => ['heading' => 'Take a walk through Klove tonight.', 'description' => 'From your sofa — the streets, the landscape and the spaces, before you ever visit.', 'videoUrl' => 'https://www.youtube.com/embed/MLpWrANjFbI?si=xdUBsJQ3tkUMv1ZX']],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'cta', 'section_type' => 'project.cta', 'content_snapshot' => ['eyebrow' => 'KLOVE   —   New Cairo', 'heading' => 'A better life begins in the right place.']],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'homes3d', 'section_type' => 'project.homes3d', 'content_snapshot' => ['heading' => 'A home that fits where you are in life.', 'description' => 'Eight ways to live at Klove — explore each one in three dimensions, room by room.', 'note' => 'Every home opens onto its own private terrace.']],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'construction', 'section_type' => 'project.construction', 'content_snapshot' => ['heading' => 'Watch your home take shape.', 'description' => "Dated updates from site, so you're never left wondering where things stand."]],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'amenities', 'section_type' => 'project.amenities', 'content_snapshot' => ['heading' => "The best parts of your day won't happen indoors."]],
            ['page_key' => 'project-klove-new-cairo', 'section_key' => 'location', 'section_type' => 'project.location', 'content_snapshot' => ['heading' => "Quiet doesn't mean far.", 'description' => 'Klove sits in Al-Qornofel, opposite Golden Square — minutes from the roads, schools and places you already use, with two gates so getting home is never a wait.', 'gateNote' => 'Two access gates — each placed for an easier way in and out', 'driveNote' => 'Drive times are indicative.']],
        ];

        foreach ($sections as $section) {
            PageSection::updateOrCreate(['page_key' => $section['page_key'], 'section_key' => $section['section_key']], [...$section, 'status' => 'published', 'published_at' => now(), 'sort_order' => 0]);
        }

        \App\Support\WebsiteCache::flushSectionSnapshots();
    }
}
