<?php

namespace App\Services;

use App\Models\MediaAsset;
use Closure;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use InvalidArgumentException;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Throwable;

/**
 * Centralizes all file handling for CMS media and private career documents.
 *
 * File names and paths are generated by this service. Callers provide only a
 * constrained directory and an upload profile, never a client-controlled path.
 */
final class MediaUploadService
{
    private const PUBLIC_DISK = 'public';
    private const PRIVATE_DISK = 'local';

    /**
     * Backwards-compatible public image entry point used by existing media CMS.
     */
    public function store(UploadedFile $file, string $directory = 'media', ?string $altText = null): MediaAsset
    {
        return $this->storePublicImage($file, $directory, $altText);
    }

    public function storePublicImage(
        UploadedFile $file,
        string $directory = 'media',
        ?string $altText = null,
        ?int $minWidth = null,
        ?int $minHeight = null,
        ?int $maxWidth = null,
        ?int $maxHeight = null,
    ): MediaAsset {
        return $this->storeValidated($file, $directory, 'public_image', [
            'alt_text' => $altText,
            'min_width' => $minWidth,
            'min_height' => $minHeight,
            'max_width' => $maxWidth,
            'max_height' => $maxHeight,
        ]);
    }

    public function storePublicBrochure(UploadedFile $file, string $directory = 'media/brochures'): MediaAsset
    {
        return $this->storeValidated($file, $directory, 'public_brochure');
    }

    public function storePublicVideo(UploadedFile $file, string $directory = 'media/videos'): MediaAsset
    {
        return $this->storeValidated($file, $directory, 'public_video');
    }

    /**
     * Backwards-compatible private CV entry point.
     */
    public function storePrivate(UploadedFile $file, string $directory = 'private/cvs'): MediaAsset
    {
        return $this->storePrivateCv($file, $directory);
    }

    public function storePrivateCv(UploadedFile $file, string $directory = 'private/cvs'): MediaAsset
    {
        return $this->storeValidated($file, $directory, 'private_cv');
    }

    /**
     * Replace a referenced asset safely. The callback must update the owning
     * record to point at the new asset inside the transaction.
     *
     * The old asset is removed only after the callback commits and only when
     * no active CMS record references it anymore.
     */
    public function replace(
        ?MediaAsset $oldAsset,
        UploadedFile $file,
        string $directory,
        string $profile,
        Closure $replaceReference,
        ?string $altText = null,
    ): MediaAsset {
        $newAsset = $this->storeValidated($file, $directory, $profile, ['alt_text' => $altText]);

        try {
            DB::transaction(fn () => $replaceReference($newAsset));
        } catch (Throwable $exception) {
            $this->delete($newAsset);
            throw $exception;
        }

        if ($oldAsset && $oldAsset->isNot($newAsset)) {
            $this->deleteIfUnreferenced($oldAsset);
        }

        return $newAsset;
    }

    /**
     * Delete an asset only if no active record references it.
     */
    public function deleteIfUnreferenced(MediaAsset $asset): bool
    {
        if ($this->isReferenced($asset)) {
            return false;
        }

        $this->delete($asset);

        return true;
    }

    public function delete(MediaAsset $asset): void
    {
        $this->assertSafePath($asset->path);
        abort_unless(in_array($asset->disk, [self::PUBLIC_DISK, self::PRIVATE_DISK], true), 404);

        Storage::disk($asset->disk)->delete($asset->path);
        $asset->delete();
    }

    /**
     * Public URLs are emitted only for the public disk and safe paths.
     */
    public function publicUrl(?MediaAsset $asset): ?string
    {
        if (! $asset || $asset->disk !== self::PUBLIC_DISK) {
            return null;
        }

        $this->assertSafePath($asset->path);

        $disk = Storage::disk(self::PUBLIC_DISK);
        if ($disk->exists($asset->path)) {
            // Use the current request base path so XAMPP subdirectory installs
            // resolve /storage correctly instead of pointing at localhost root.
            if (app()->bound('request')) {
                $request = request();
                return rtrim($request->getSchemeAndHttpHost().$request->getBaseUrl(), '/').'/storage/'.ltrim($asset->path, '/');
            }

            return $disk->url($asset->path);
        }

        // Legacy seeded assets still live in public/assets. Keep their
        // presentation unchanged while all new uploads use public/storage.
        if (Str::startsWith($asset->path, 'assets/')) {
            return asset('assets/'.basename($asset->path));
        }

        return null;
    }

    /**
     * Private CV download helper. It refuses public assets and traversal paths.
     */
    public function downloadPrivate(MediaAsset $asset): StreamedResponse
    {
        abort_unless($asset->disk === self::PRIVATE_DISK, 404);
        $this->assertSafePath($asset->path);
        abort_unless(Storage::disk(self::PRIVATE_DISK)->exists($asset->path), 404);

        return Storage::disk(self::PRIVATE_DISK)->download($asset->path, $asset->original_name);
    }

    private function storeValidated(UploadedFile $file, string $directory, string $profile, array $options = []): MediaAsset
    {
        $this->assertSafeDirectory($directory);

        $definition = $this->profile($profile);
        $extension = strtolower((string) pathinfo($file->getClientOriginalName(), PATHINFO_EXTENSION));
        $mime = strtolower((string) ($file->getMimeType() ?: $file->getClientMimeType()));
        $size = (int) ($file->getSize() ?: strlen((string) $file->get()));

        if (! in_array($extension, $definition['extensions'], true)) {
            throw new InvalidArgumentException('The uploaded file extension is not allowed.');
        }

        if (! in_array($mime, $definition['mimes'], true)) {
            throw new InvalidArgumentException('The uploaded file MIME type is not allowed.');
        }

        if ($size > $definition['max_size']) {
            throw new InvalidArgumentException('The uploaded file is too large.');
        }

        $contents = (string) $file->get();
        if ($profile === 'public_image' && $extension === 'svg') {
            $this->assertSafeSvg($contents);
        }

        [$width, $height] = $this->imageDimensions($contents, $extension, $profile);
        $this->assertDimensions($width, $height, $options);

        if ($profile === 'public_image' && $extension !== 'svg') {
            [$contents, $extension, $mime, $size, $width, $height] = $this->optimizePublicImage(
                $contents,
                $extension,
                $width,
                $height,
            );
        }

        $path = trim($directory, '/').'/' . Str::lower((string) Str::uuid()).'.'.$extension;
        $disk = $definition['disk'];

        try {
            if (! Storage::disk($disk)->put($path, $contents)) {
                throw new InvalidArgumentException('The uploaded file could not be stored.');
            }

            return MediaAsset::create([
                'disk' => $disk,
                'path' => $path,
                'original_name' => basename($file->getClientOriginalName()),
                'mime_type' => $mime,
                'size_bytes' => $size,
                'width' => $width,
                'height' => $height,
                'alt_text' => $options['alt_text'] ?? null,
                'uploaded_by' => auth()->id(),
            ]);
        } catch (Throwable $exception) {
            Storage::disk($disk)->delete($path);
            throw $exception;
        }
    }

    /**
     * @return array{disk: string, max_size: int, extensions: array<int, string>, mimes: array<int, string>}
     */
    private function profile(string $profile): array
    {
        return match ($profile) {
            'public_image' => [
                'disk' => self::PUBLIC_DISK,
                'max_size' => 25 * 1024 * 1024,
                'extensions' => ['jpg', 'jpeg', 'png', 'webp', 'svg'],
                'mimes' => ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml'],
            ],
            'public_brochure' => [
                'disk' => self::PUBLIC_DISK,
                'max_size' => 20 * 1024 * 1024,
                'extensions' => ['pdf'],
                'mimes' => ['application/pdf'],
            ],
            'public_video' => [
                'disk' => self::PUBLIC_DISK,
                'max_size' => 50 * 1024 * 1024,
                'extensions' => ['mp4'],
                'mimes' => ['video/mp4', 'application/mp4'],
            ],
            'private_cv' => [
                'disk' => self::PRIVATE_DISK,
                'max_size' => 10 * 1024 * 1024,
                'extensions' => ['pdf', 'doc', 'docx'],
                'mimes' => [
                    'application/pdf',
                    'application/msword',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                ],
            ],
            default => throw new InvalidArgumentException('Unknown upload profile.'),
        };
    }

    private function imageDimensions(string $contents, string $extension, string $profile): array
    {
        if ($profile !== 'public_image' || $extension === 'svg') {
            return [null, null];
        }

        $dimensions = @getimagesizefromstring($contents);
        if (! $dimensions) {
            throw new InvalidArgumentException('The uploaded image is invalid.');
        }

        return [$dimensions[0], $dimensions[1]];
    }

    /**
     * Resize raster uploads to a sensible maximum and store them as WebP.
     * This keeps CMS content fast even when an editor uploads a camera-original
     * PNG or JPEG.
     *
     * @return array{string, string, string, int, int, int}
     */
    private function optimizePublicImage(string $contents, string $extension, int $width, int $height): array
    {
        if (! function_exists('imagecreatefromstring') || ! function_exists('imagewebp')) {
            throw new InvalidArgumentException('The server image processor is not available.');
        }

        $source = @imagecreatefromstring($contents);
        if (! $source) {
            throw new InvalidArgumentException('The uploaded image is invalid.');
        }

        $maxDimension = 2560;
        $scale = min(1, $maxDimension / max($width, $height));
        $targetWidth = max(1, (int) round($width * $scale));
        $targetHeight = max(1, (int) round($height * $scale));
        $target = imagecreatetruecolor($targetWidth, $targetHeight);

        imagealphablending($target, false);
        imagesavealpha($target, true);
        imagefill($target, 0, 0, imagecolorallocatealpha($target, 0, 0, 0, 127));
        imagecopyresampled($target, $source, 0, 0, 0, 0, $targetWidth, $targetHeight, $width, $height);

        ob_start();
        $encoded = imagewebp($target, null, 82);
        $optimized = (string) ob_get_clean();
        imagedestroy($source);
        imagedestroy($target);

        if (! $encoded || $optimized === '') {
            throw new InvalidArgumentException('The uploaded image could not be optimized.');
        }

        return [$optimized, 'webp', 'image/webp', strlen($optimized), $targetWidth, $targetHeight];
    }

    private function assertDimensions(?int $width, ?int $height, array $options): void
    {
        if ($width === null || $height === null) {
            return;
        }

        if (isset($options['min_width']) && $width < $options['min_width']) {
            throw new InvalidArgumentException('The image width is too small.');
        }
        if (isset($options['min_height']) && $height < $options['min_height']) {
            throw new InvalidArgumentException('The image height is too small.');
        }
        if (isset($options['max_width']) && $width > $options['max_width']) {
            throw new InvalidArgumentException('The image width is too large.');
        }
        if (isset($options['max_height']) && $height > $options['max_height']) {
            throw new InvalidArgumentException('The image height is too large.');
        }
    }

    private function assertSafeSvg(string $contents): void
    {
        if (preg_match('/<\/?(?:script|foreignObject|iframe|object|embed)\b/i', $contents)
            || preg_match('/\bon[a-z0-9_-]+\s*=|javascript\s*:|data\s*:\s*text\/html|href\s*=\s*["\']https?:/i', $contents)) {
            throw new InvalidArgumentException('The SVG contains unsafe content.');
        }

        $document = new \DOMDocument();
        $document->preserveWhiteSpace = false;
        $document->formatOutput = false;
        libxml_use_internal_errors(true);
        $loaded = $document->loadXML($contents, LIBXML_NONET | LIBXML_NOERROR | LIBXML_NOWARNING);
        libxml_clear_errors();

        if (! $loaded || strtolower((string) $document->documentElement?->localName) !== 'svg') {
            throw new InvalidArgumentException('The SVG document is invalid.');
        }
    }

    private function assertSafeDirectory(string $directory): void
    {
        if ($directory === '' || str_contains($directory, '\\') || str_contains($directory, '..')
            || str_starts_with($directory, '/') || preg_match('/[\x00-\x1F\x7F]/', $directory)) {
            throw new InvalidArgumentException('The upload directory is invalid.');
        }

        foreach (explode('/', trim($directory, '/')) as $segment) {
            if ($segment === '' || $segment === '.' || $segment === '..' || ! preg_match('/^[A-Za-z0-9_-]+$/', $segment)) {
                throw new InvalidArgumentException('The upload directory is invalid.');
            }
        }
    }

    private function assertSafePath(string $path): void
    {
        if ($path === '' || str_contains($path, '\\') || str_contains($path, '..')
            || str_starts_with($path, '/') || preg_match('/[\x00-\x1F\x7F]/', $path)
            || ! preg_match('/^[A-Za-z0-9._\/-]+$/', $path)) {
            throw new InvalidArgumentException('The stored file path is invalid.');
        }
    }

    private function isReferenced(MediaAsset $asset): bool
    {
        $references = [
            ['projects', 'hero_image_id'], ['projects', 'logo_id'], ['projects', 'brochure_id'], ['projects', 'map_image_id'],
            ['media_posts', 'featured_image_id'], ['media_posts', 'open_graph_image_id'], ['photo_gallery_items', 'media_asset_id'], ['testimonials', 'media_asset_id'],
            ['project_galleries', 'media_asset_id'], ['project_updates', 'media_asset_id'], ['job_applications', 'resume_media_id'],
            ['internship_applications', 'resume_media_id'], ['general_cv_submissions', 'resume_media_id'],
        ];

        foreach ($references as [$table, $column]) {
            if (DB::table($table)->whereNull('deleted_at')->where($column, $asset->getKey())->exists()) {
                return true;
            }
        }

        return false;
    }
}
