import { Head, Link, useForm, usePage } from '@inertiajs/react';
import type { PageProps } from '@/types';
import AdminLayout from '@/layouts/AdminLayout';
import { Breadcrumbs, FormField, Notification } from '@/components/admin/AdminLayoutParts';

type Testimonial = { id?: number; name: string; role: string; quote: string; sort_order: number; is_published: boolean; image?: string | null };

export default function Form({ testimonial }: { testimonial: Testimonial | null }) {
    const { flash } = usePage<PageProps<{ flash?: { success?: string } }>>().props;
    const { data, setData, post, put, processing, errors } = useForm({ name: testimonial?.name ?? '', role: testimonial?.role ?? '', quote: testimonial?.quote ?? '', sort_order: testimonial?.sort_order ?? 0, is_published: testimonial?.is_published ?? true, image: null as File | null });
    const submit = (event: React.FormEvent) => { event.preventDefault(); const options = { forceFormData: true }; testimonial?.id ? put(`/admin/pages/home/testimonials/${testimonial.id}`, options) : post('/admin/pages/home/testimonials', options); };

    return <AdminLayout><Head title={testimonial ? 'Edit Testimonial' : 'Add Testimonial'} /><div className="mx-auto max-w-3xl space-y-8"><div><Breadcrumbs items={['Dashboard', 'Website Pages', 'Home Page', 'Testimonials', testimonial ? 'Edit' : 'Add']} /><h1 className="mt-2 text-2xl font-bold text-white sm:text-3xl">{testimonial ? 'Edit testimonial' : 'Add testimonial'}</h1></div><Notification message={flash?.success} /><form onSubmit={submit} encType="multipart/form-data" className="space-y-5 rounded-2xl border border-white/10 bg-[#161619]/90 p-6 shadow-xl"><div className="grid gap-5 sm:grid-cols-2"><FormField label="Name" error={errors.name}><input required value={data.name} onChange={(event) => setData('name', event.target.value)} className={inputClass} /></FormField><FormField label="Role" error={errors.role}><input value={data.role} onChange={(event) => setData('role', event.target.value)} className={inputClass} /></FormField></div><FormField label="Quote" error={errors.quote}><textarea required rows={7} value={data.quote} onChange={(event) => setData('quote', event.target.value)} className={inputClass} /></FormField><div className="grid gap-5 sm:grid-cols-2"><FormField label="Sort order" error={errors.sort_order}><input type="number" min="0" value={data.sort_order} onChange={(event) => setData('sort_order', Number(event.target.value))} className={inputClass} /></FormField><FormField label="Profile image" error={errors.image}><input type="file" accept="image/*" onChange={(event) => setData('image', event.target.files?.[0] ?? null)} className={fileClass} />{testimonial?.image && <img src={testimonial.image} alt="Current testimonial" className="mt-3 h-24 w-24 rounded-lg object-cover grayscale" />}</FormField></div><label className="flex items-center gap-3 text-sm text-white/75"><input type="checkbox" checked={data.is_published} onChange={(event) => setData('is_published', event.target.checked)} className="size-4 rounded border-white/20 bg-white/10 text-[#C5A880]" /> Published on the home page</label><div className="flex gap-3 pt-2"><button disabled={processing} className="rounded-xl bg-gradient-to-r from-[#C5A880] to-[#D4AF37] px-5 py-3 text-sm font-semibold text-black disabled:opacity-50">{testimonial ? 'Save changes' : 'Create testimonial'}</button><Link href="/admin/pages/home/testimonials" className="rounded-xl border border-white/15 px-5 py-3 text-sm text-white/75 hover:text-white">Cancel</Link></div></form></div></AdminLayout>;
}

const inputClass = 'w-full rounded-xl border border-white/15 bg-[#1e1e22] px-4 py-3 text-sm text-white outline-none transition focus:border-[#C5A880] focus:ring-1 focus:ring-[#C5A880]/30';
const fileClass = 'block w-full rounded-xl border border-white/15 bg-[#1e1e22] px-3 py-3 text-sm text-white/60 file:mr-3 file:rounded-lg file:border-0 file:bg-[#C5A880]/20 file:px-3 file:py-1 file:text-xs file:font-semibold file:text-[#C5A880]';
