import { Link, Head, router, usePage } from '@inertiajs/react';
import type { PageProps } from '@/types';
import AdminLayout from '@/layouts/AdminLayout';
import { Breadcrumbs, Notification, Pagination, SearchInput, StatusBadge } from '@/components/admin/AdminLayoutParts';

type Post = { id: number; title: string; slug: string; type: string; category: string | null; published: boolean; featured: boolean; image: string | null };
type Page = { data: Post[]; current_page: number; last_page: number };

export default function Index({ posts, categories, filters }: { posts: Page; categories: Array<{ id: number; name: string }>; filters: Record<string, string | null> }) {
    const { flash } = usePage<PageProps<{ flash?: { success?: string } }>>().props;
    return <AdminLayout><Head title="Media Posts" /><div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><Breadcrumbs items={['Admin', 'Media', 'Posts']} /><h1 className="mt-3 text-3xl font-semibold">Media posts</h1></div><Link href="/admin/media/posts/create" className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white">Create post</Link></div><Notification message={flash?.success} /><div className="flex flex-col gap-3 sm:flex-row"><SearchInput value={filters.search ?? ''} onChange={(value) => router.get('/admin/media/posts', { ...filters, search: value }, { preserveState: true })} /><select defaultValue={filters.type ?? ''} onChange={(event) => router.get('/admin/media/posts', { ...filters, type: event.target.value }, { preserveState: true })} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="">All types</option><option value="press">Press</option><option value="blog">Blog</option></select><select defaultValue={filters.category ?? ''} onChange={(event) => router.get('/admin/media/posts', { ...filters, category: event.target.value }, { preserveState: true })} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-950"><table className="w-full text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Title</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{posts.data.map((post) => <tr key={post.id} className="border-b border-slate-800/70"><td className="px-4 py-4 font-medium">{post.title}</td><td className="px-4 py-4 text-slate-400">{post.type}</td><td className="px-4 py-4 text-slate-400">{post.category}</td><td className="px-4 py-4"><StatusBadge status={post.published ? 'Published' : 'Draft'} /></td><td className="px-4 py-4"><Link href={`/admin/media/posts/${post.id}/edit`} className="text-emerald-400 hover:text-emerald-300">Edit</Link></td></tr>)}</tbody></table></div><Pagination current={posts.current_page} total={posts.last_page} /></div></AdminLayout>;
}
