import { Head, useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import type { PageProps } from '@/types';
import AdminLayout from '@/layouts/AdminLayout';
import { Breadcrumbs, FormField, Notification } from '@/components/admin/AdminLayoutParts';

type Copy = { eyebrow?: string; heading?: string; body?: string };

export default function AboutStory({ translations, image }: { translations: { en?: Copy; ar?: Copy }; image: string | null }) {
    const { flash } = usePage<PageProps<{ flash?: { success?: string } }>>().props;
    const [language, setLanguage] = useState<'en' | 'ar'>('en');
    const form = useForm<{ translations: { en: Copy; ar: Copy }; image: File | null }>({ translations: { en: translations.en ?? {}, ar: translations.ar ?? {} }, image: null });
    const copy = form.data.translations[language];
    const update = (key: keyof Copy, value: string) => form.setData('translations', { ...form.data.translations, [language]: { ...copy, [key]: value } });
    const submit = (event: React.FormEvent) => { event.preventDefault(); form.transform((payload) => ({ ...payload, _method: 'put' })); form.post('/admin/pages/about/story', { forceFormData: true, preserveScroll: true }); };

    return <AdminLayout><Head title="About Story" /><div className="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><div><Breadcrumbs items={['Dashboard', 'Website Pages', 'About Us', 'Our Story']} /><h1 className="mt-3 text-3xl font-semibold">Our story</h1><p className="mt-2 text-sm text-slate-400">Manage the story copy and image shown on the public About page.</p></div><Notification message={flash?.success} /><form onSubmit={submit} encType="multipart/form-data" className="space-y-6"><div className="flex gap-2 border-b border-slate-800 pb-3"><button type="button" onClick={() => setLanguage('en')} className={`rounded-lg px-4 py-2 text-sm ${language === 'en' ? 'bg-gold text-black' : 'bg-white/5 text-white/60'}`}>English</button><button type="button" onClick={() => setLanguage('ar')} className={`rounded-lg px-4 py-2 text-sm ${language === 'ar' ? 'bg-gold text-black' : 'bg-white/5 text-white/60'}`}>Arabic</button></div><section dir={language === 'ar' ? 'rtl' : 'ltr'} className="grid gap-5 rounded-xl border border-slate-800 bg-slate-950 p-6"><FormField label="Eyebrow"><input value={copy.eyebrow ?? ''} onChange={(event) => update('eyebrow', event.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2" /></FormField><FormField label="Heading"><input value={copy.heading ?? ''} onChange={(event) => update('heading', event.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2" /></FormField><FormField label="Body"><textarea rows={10} value={copy.body ?? ''} onChange={(event) => update('body', event.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2" /></FormField></section><section className="rounded-xl border border-slate-800 bg-slate-950 p-6"><h2 className="text-xl font-semibold">Story image</h2>{image && <img src={image} alt="Current story" className="mt-4 h-64 w-full rounded-xl object-cover" />}<input type="file" accept="image/*" onChange={(event) => form.setData('image', event.target.files?.[0] ?? null)} className="mt-4 block w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm text-slate-300" /></section><button type="submit" disabled={form.processing} className="rounded-lg bg-emerald-600 px-5 py-3 text-sm font-medium text-white disabled:opacity-50">{form.processing ? 'Saving...' : 'Save story'}</button></form></div></AdminLayout>;
}
