import { Link, Head, router, usePage } from '@inertiajs/react';
import type { PageProps } from '@/types';
import AdminLayout from '@/layouts/AdminLayout';
import { Breadcrumbs, Notification, Pagination, SearchInput, StatusBadge } from '@/components/admin/AdminLayoutParts';
import { useI18n } from '@/i18n';
type Post = { id: number; title: string; slug: string; type: string; category: string | null; published: boolean; featured: boolean; image: string | null };
type Page = { data: Post[]; current_page: number; last_page: number };
export default function Index({ posts, categories, filters }: { posts: Page; categories: Array<{ id: number; name: string }>; filters: Record<string, string | null> }) {
    const { flash } = usePage<PageProps<{ flash?: { success?: string } }>>().props;
    const { locale } = useI18n();
    const ar = locale === 'ar';
    const tr = (v: string) => ar ? ({ 'Media Posts': 'منشورات الإعلام', 'Media posts': 'منشورات الإعلام', Dashboard: 'لوحة التحكم', Media: 'الإعلام', Posts: 'المنشورات', 'Create post': 'إنشاء منشور', 'All types': 'كل الأنواع', Press: 'صحفي', Blog: 'مدونة', 'All categories': 'كل التصنيفات', Title: 'العنوان', Type: 'النوع', Category: 'التصنيف', Status: 'الحالة', Actions: 'الإجراءات', Edit: 'تعديل', Published: 'منشور', Draft: 'مسودة', 'Press releases': 'البيانات الصحفية', Blogs: 'المدونات' } as Record<string, string>)[v] ?? v : v;
    const categoryName = (v: string | null) => ar ? ({ 'Press releases': 'البيانات الصحفية', Blogs: 'المدونات' } as Record<string, string>)[v ?? ''] ?? v : v;
    return <AdminLayout><Head title={tr('Media Posts')} /><div className="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><Breadcrumbs items={['Dashboard', 'Media', 'Posts'].map(tr)} /><h1 className="mt-3 text-3xl font-semibold">{tr('Media posts')}</h1></div><Link href="/admin/media/posts/create" className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white">{tr('Create post')}</Link></div><Notification message={flash?.success} /><div className="flex flex-col gap-3 sm:flex-row"><SearchInput value={filters.search ?? ''} className="sm:w-52" placeholder={ar ? 'ابحث...' : 'Search...'} onChange={(value) => router.get('/admin/media/posts', { ...filters, search: value }, { preserveState: true })} /><select defaultValue={filters.type ?? ''} onChange={(e) => router.get('/admin/media/posts', { ...filters, type: e.target.value }, { preserveState: true })} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm sm:w-44"><option value="">{tr('All types')}</option><option value="press">{tr('Press')}</option><option value="blog">{tr('Blog')}</option></select><select defaultValue={filters.category ?? ''} onChange={(e) => router.get('/admin/media/posts', { ...filters, category: e.target.value }, { preserveState: true })} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm sm:w-56"><option value="">{tr('All categories')}</option>{categories.map((c) => <option key={c.id} value={c.id}>{categoryName(c.name)}</option>)}</select></div><div className="overflow-x-auto rounded-xl border border-slate-800 bg-slate-950"><table className="w-full text-center text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3 text-center">{tr('Title')}</th><th className="px-4 py-3 text-center">{tr('Type')}</th><th className="px-4 py-3 text-center">{tr('Category')}</th><th className="px-4 py-3 text-center">{tr('Status')}</th><th className="px-4 py-3 text-center">{tr('Actions')}</th></tr></thead><tbody>{posts.data.map((p) => <tr key={p.id} className="border-b border-slate-800/70"><td className="px-4 py-4 font-medium">{p.title}</td><td className="px-4 py-4 text-slate-400">{tr(p.type === 'press' ? 'Press' : 'Blog')}</td><td className="px-4 py-4 text-slate-400">{categoryName(p.category)}</td><td className="px-4 py-4"><StatusBadge status={p.published ? tr('Published') : tr('Draft')} /></td><td className="px-4 py-4"><Link href={`/admin/media/posts/${p.id}/edit`} className="text-emerald-400 hover:text-emerald-300">{tr('Edit')}</Link></td></tr>)}</tbody></table></div><Pagination current={posts.current_page} total={posts.last_page} /></div></AdminLayout>;
}
