import Checkbox from '@/components/Checkbox';
import InputError from '@/components/InputError';
import InputLabel from '@/components/InputLabel';
import PrimaryButton from '@/components/PrimaryButton';
import TextInput from '@/components/TextInput';
import GuestLayout from '@/layouts/GuestLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { FormEventHandler, useState } from 'react';
import { Mail, Lock, Eye, EyeOff, ShieldCheck, Loader2 } from 'lucide-react';
import { useI18n } from '@/i18n';

export default function Login({ status, canResetPassword }: { status?: string; canResetPassword: boolean }) {
    const { locale, dir } = useI18n(); const ar = locale === 'ar';
    const c = ar ? { title: 'تسجيل الدخول', subtitle: 'أدخل بيانات حسابك للوصول إلى لوحة التحكم', email: 'البريد الإلكتروني', password: 'كلمة المرور', remember: 'تذكرني', forgot: 'نسيت كلمة المرور؟', login: 'تسجيل الدخول', checking: 'جارٍ التحقق...', hide: 'إخفاء كلمة المرور', show: 'إظهار كلمة المرور' } : { title: 'Sign in', subtitle: 'Enter your account details to access the dashboard', email: 'Email', password: 'Password', remember: 'Remember me', forgot: 'Forgot your password?', login: 'Sign in', checking: 'Signing in...', hide: 'Hide password', show: 'Show password' };
    const [showPassword, setShowPassword] = useState(false);
    const { data, setData, post, processing, errors, reset } = useForm({ email: '', password: '', remember: false as boolean });
    const submit: FormEventHandler = (e) => { e.preventDefault(); post(route('login'), { onFinish: () => reset('password') }); };
    return <GuestLayout><div dir={dir}><Head title={`${c.title} - LARZ`} /><div className="mb-6 text-center"><div className="mx-auto mb-3 flex size-12 items-center justify-center rounded-xl border border-[#C5A880]/30 bg-[#C5A880]/10 text-[#C5A880]"><ShieldCheck className="size-6" /></div><h1 className="text-xl font-bold tracking-wide text-white sm:text-2xl">{c.title}</h1><p className="mt-1 text-xs text-white/50">{c.subtitle}</p></div>{status && <div className="mb-6 rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3.5 text-center text-xs font-medium text-emerald-400">{status}</div>}<form onSubmit={submit} className="space-y-5"><div><InputLabel htmlFor="email" value={c.email} /><div className="relative mt-1"><div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3.5 text-white/40"><Mail className="size-4" /></div><TextInput id="email" type="email" name="email" value={data.email} className="h-[50px] pl-10 pr-4" placeholder="admin@larz.com" autoComplete="username" isFocused onChange={(e) => setData('email', e.target.value)} /></div><InputError message={errors.email} className="mt-2 text-xs" /></div><div><InputLabel htmlFor="password" value={c.password} /><div className="relative mt-1"><div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3.5 text-white/40"><Lock className="size-4" /></div><TextInput id="password" type={showPassword ? 'text' : 'password'} name="password" value={data.password} className="h-[50px] pl-10 pr-10" placeholder="••••••••" autoComplete="current-password" onChange={(e) => setData('password', e.target.value)} /><button type="button" onClick={() => setShowPassword((v) => !v)} className="absolute inset-y-0 right-0 flex items-center pr-3.5 text-white/40 hover:text-white" aria-label={showPassword ? c.hide : c.show}>{showPassword ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></div><InputError message={errors.password} className="mt-2 text-xs" /></div><div className="flex items-center justify-between pt-1"><label className="flex cursor-pointer items-center gap-2"><Checkbox name="remember" checked={data.remember} onChange={(e) => setData('remember', e.target.checked)} /><span className="text-xs text-white/70">{c.remember}</span></label>{canResetPassword && <Link href={route('password.request')} className="text-xs text-[#C5A880] hover:text-amber-300 hover:underline">{c.forgot}</Link>}</div><div className="pt-2"><PrimaryButton className="h-[50px]" disabled={processing}>{processing ? <span className="flex items-center gap-2"><Loader2 className="size-4 animate-spin" />{c.checking}</span> : c.login}</PrimaryButton></div></form></div></GuestLayout>;
}
